# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b71afe1adf39012567fce355aa34f3a38dc5f0b3d9fa2e4a7b030d60f122edffe4da36ef44279d666963df088e223de29ab3dd8f28e5a9825f705d6a89905a3f

test:
  secret_key_base: bf362c7b61eb229e9ab4b1577d9d9543bf938381cc4b9e78f5ad7b1f1ecfd82cf06950fc62acade5309b1a6f538e4156e1716655cea0b86f23591f08b8b4f133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
